In [1]:
pip install numpy

In [3]:
import numpy as np


In [4]:
print(np.__version__)

2.1.3


In [6]:
import numpy as np
arr =np.array([1,2,3,4,5,6,])
print(arr)

[1 2 3 4 5 6]


In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6,]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np
arr =np.array([[1,2],[3,4],[5,6]])
print(arr)
print(type)

[[1 2]
 [3 4]
 [5 6]]
<class 'type'>


In [14]:
import numpy as np
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
import numpy as np
arr = np.zeros((10,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
arr = np.ones((3,1))
arr

array([[1.],
       [1.],
       [1.]])

In [17]:
arr=np.full((4,7),9)
arr


array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [20]:
arr = np.empty((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
import numpy as np
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
import numpy as np
arr = np.arange(2,500,2)
arr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [41]:
arr = np.arange(1,500,2)
arr

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
       209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
       235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259,
       261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285,
       287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311,
       313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337,
       339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 36

In [43]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [44]:
arr = np.random.rand(10)
arr

array([0.20175215, 0.29164844, 0.28598095, 0.52840752, 0.77172473,
       0.25856259, 0.55648424, 0.25180302, 0.69714854, 0.88304038])

In [45]:
arr = np.random.randn(10)
arr

array([-0.8701999 , -0.28414957,  1.72498513,  0.48967841,  0.52013718,
        0.50291818, -0.19209269,  0.21041774, -1.45101536,  1.35421486])

In [52]:
import numpy as np
colours = ["red","green","pink","orange","blue","white","black"]
print(np.random.choice(colours,2))


['red' 'green']


In [54]:
ray([1,2,3])arr = np.ar
new = arr.copy()
new[1] = 100
print("Array value is:", arr)
print("copy value is:",new)

Array value is: [1 2 3]
copy value is: [  1 100   3]


In [57]:
import numpy as np
arr = np.array([5,10,15,20,25,30])
arr += 10
print("Updated array value is:", arr)

Updated array value is: [15 20 25 30 35 40]


In [58]:
import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.add(A,B))

[ 7  9 11 13 15]


In [61]:
import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.subtract(A,B))

[-5 -5 -5 -5 -5]


In [62]:
import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.multiply(A,B))

[ 6 14 24 36 50]


In [63]:
import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.divide(A,B))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [64]:
import numpy as np
A=np.array([1,2,3,4,5,])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))

130


In [65]:
import numpy as np
Arr = np.array([1,2,3,4,5,6,7,8,9])
print(sum(Arr))

45


In [68]:
import numpy as np
Arr = np.array([1,2,9,13,3,4,5,6,7,8,9])
print(np.sort(Arr))

[ 1  2  3  4  5  6  7  8  9  9 13]


In [69]:
import numpy as np
Arr = np.array([1,2,9,13,3,4,5,6,7,8,9])
print(np.unique(Arr))

[ 1  2  3  4  5  6  7  8  9 13]


In [71]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.size)
print(arr.dtype)

11
int64


In [73]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.ndim)
print(arr[1,7])

(9,)
1


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [74]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Original Array", arr)
newarr = arr.reshape(3,5)
print("Reshaped Array", newarr)

Original Array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped Array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
